on:
  push:
    paths: 
      - 'main.tex'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile TeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
